### PR TITLE
Add edge cases für game titles

### PR DESCRIPTION
**Pull request by Pfuenzle**
This should cover most edge cases.
I havbe some roms with e.g. __Wii__ in the filename, which will not be picked up by this, but I was not sure how far the parsing code should be specified

### CODE REVIEW

**Comment by grimsi** [comment]
Wow, thanks a lot for your contribution!

I would like to merge it, but the source code of the `IgdbWrapper` looks a little messed up.
I can take care of this if you want tho.

**Comment by Pfuenzle** [comment]
oh thanks for the catch, not sure what happened there.
No problem, I fixed it, should be fine now

**Comment by grimsi** [comment]
Thanks again for both of your contributions @Pfuenzle @tr7zw !

I will add some test cases just to be sure it all works as expected, but my first manual tests did not reveal any issues.

**Comment by tr7zw** [comment]
I wanted to add tests to my code, but at that time I wasn't able to find any. I can do that in a new PR.

**Comment by grimsi** [comment]
Yeah, I didn't have any tests at that time (since it started as a personal hobby project I was too lazy to add tests).
However since there were quite a few bug reports in the last couple of days, I am currently focusing on implementing unit and some integration tests (at least for the backend).
If you want to contribute, here is the pull request I am currently working on: https://github.com/grimsi/gameyfin/pull/70

**Pull request merged**
